######################################################################
# Automatically generated by qmake (2.01a) ?? 2. ??? 00:34:16 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main_dialog.h
FORMS += main_dialog.ui
SOURCES += main.cpp main_dialog.cpp
