######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 3 15:48:47 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl
OBJECTS_DIR = ../tmp

# Input
HEADERS += main_dialog.h slow_gl_view.h
FORMS += main_dialog.ui
SOURCES += main.cpp main_dialog.cpp slow_gl_view.cpp
