######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 10 10:39:53 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ../../src2
INCLUDEPATH += . ../../src2

# Input
SOURCES += main.cpp storage3d.cpp
