######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 8 18:32:59 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl
QMAKE_CXXFLAGS += -O3
OBJECTS_DIR = ../tmp

# Input
FORMS += main_dialog.ui
HEADERS += gl_view.h main_dialog.h
SOURCES += gl_view.cpp main.cpp main_dialog.cpp
